### ISSUE TITLE
Backup files only contain a link

### ISSUE THREAD

**Issue by oparisy** [Ahtenus/minecraft-init#1]
The backup files created by the crontab entry "/etc/init.d/minecraft backup" only contain a link :
```$ tar -jtvf backup/world_2011.05.22.tar.bz2
lrwxrwxrwx minecraft/minecraft 0 2011-05-21 08:06 world -> /dev/shm/world

```
```

**Comment by Ahtenus** [comment]
Thanks for pointing it out, didn't notice it when I started using ramdisk.

**Comment by oparisy** [comment]
Adding the "h" option to tar worked fine for me.

Regards.
