### ISSUE TITLE
Could not get to work with su, changed to sudo

### ISSUE THREAD

**Issue by ghost** [Ahtenus/minecraft-init#11]
I don't know if I did something wrong, but `as_user()` does not work for me if it uses `su - $USERNAME -c "$1"`. All such commands just silently fail. I am using Debian Wheezy.

`as_user()` starts working if I replace the `su` line with `sudo -u $USERNAME bash -c "$1"`.

**Comment by Benni-chan** [comment]
do you have any errors in your syslog? would be interesting to see, why it failed.

i'm thinking about using the sudo method, but include a fallback for those, that don't have sudo installed.

**Comment by ghost** [comment]
No errors in syslog or auth.log. Relevant lines from auth.log:

```
Sep 24 10:26:33 kikai su[28720]: Successful su for minecraft by root
Sep 24 10:26:33 kikai su[28720]: + /dev/pts/4 root:minecraft
Sep 24 10:26:33 kikai su[28720]: pam_unix(su:session): session opened for user minecraft by (uid=0)
Sep 24 10:26:33 kikai su[28720]: pam_unix(su:session): session closed for user minecraft
Sep 24 10:26:33 kikai su[28729]: Successful su for minecraft by root
Sep 24 10:26:33 kikai su[28729]: + /dev/pts/4 root:minecraft
Sep 24 10:26:33 kikai su[28729]: pam_unix(su:session): session opened for user minecraft by (uid=0)
Sep 24 10:26:33 kikai su[28729]: pam_unix(su:session): session closed for user minecraft
Sep 24 10:26:33 kikai su[28755]: Successful su for minecraft by root
Sep 24 10:26:33 kikai su[28755]: + /dev/pts/4 root:minecraft
Sep 24 10:26:33 kikai su[28755]: pam_unix(su:session): session opened for user minecraft by (uid=0)
Sep 24 10:26:33 kikai su[28755]: pam_unix(su:session): session closed for user minecraft
```

**Comment by karrth** [comment]
If you execute the su - commands manually in terminal, what happens?  What shell is your minecraft account running as default?

**Comment by ghost** [comment]
Executing manually from the terminal also fails silently. The default shell is actually a good point, as I have it set to /bin/false because I don't need to ever log in to that account.

From /etc/passwd:
`minecraft:x:1002:1002::/opt/minecraft:/bin/false`

**Comment by karrth** [comment]
When I set my minecraft account to /bin/false, the commands also fail for me.  There's your issue!

**Comment by ghost** [comment]
I wonder why that makes a difference. Maybe `screen` is not in `$PATH` if your shell is `/bin/false`? Perhaps if the script called `/usr/bin/screen` by full path or changed the relevant line to `su - $USERNAME -c "bash -c \"$1\""`. Using `sudo` is probably not a good idea because it is not guaranteed to be installed.

**Comment by karrth** [comment]
I would say it's because when you do "su -" you're switching to that username and it's environment.  If the shell is /bin/false, then it cannot switch to that shell, and therefore fails.  You can see this by trying to just "su - mineraft" in terminal.

**Comment by ghost** [comment]
Yeah, you are right. Makes sense.

I'm closing the issue. Using sudo worked for me, but other than that, having the minecraft username use /bin/false as default shell will currently not work with this script :)

**Comment by jmcaffee** [comment]
I experienced this issue as well and fixed it by changing:
```su - $USERNAME -c "$1"

``````
To

```su - $USERNAME -s /bin/bash -c "$1"
``````

-s indicates which shell to use. This allows me to leave the user's shell as bin/false

**Comment by Rovanion** [comment]
Having the user shell set to /bin/false gives a false sense of security. It prevents shell login but since the user is still allowed to connect and authenticate trough ssh there are still other options for mischef available. Read this for further reference: http://www.semicomplete.com/articles/ssh-security/

Edit your /etc/ssh/sshd_config to disallow your minecraft user to connect. Or even better, only allow specified users.
