### ISSUE TITLE
Rogue pidfile found!

### ISSUE THREAD

**Issue by Den-Valk** [Ahtenus/minecraft-init#113]
My terminal readout is:

minecraft@MineCraft:~$ /etc/init.d/minecraft start
OldWorld copied to ram
world copied to ram
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try`grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
Rogue pidfile found!
^C
SIGINIT CALLED - FORCE EXITING!
KILLING SERVER PROCESSES!!!
Killing PID:  6313
Terminated
minecraft@MineCraft:~$ 

My config is uploaded at 
http://pastebin.com/vyaVT8TN

I could really use some help here. I think I am in over my head. Thanks

-J

**Comment by jbondhus** [comment]
Can you run "bash -x /etc/init.d/minecraft start" and put the output on pastebin?

**Comment by Den-Valk** [comment]
Will do. Just a moment.

**Comment by jbondhus** [comment]
Thanks, that will give the debug information, which will be much more useful to find problems with.

**Comment by Den-Valk** [comment]
Requested pastebin dump is http://pastebin.com/9ktkC958
Thanks

**Comment by jbondhus** [comment]
Are you running the latest version of the script? Also, try removing the PID file from your minecraft directory (/home/minecraft/MineCraftServer/ServerXavior/Xavior.pid), then starting it again.

**Comment by Den-Valk** [comment]
Yes I am running the latest version. I just tried to remove the .pid with 
rm /home/minecraft/MineCraftServer/ServerXavior/Xavior.pid
and the end result was the same.

**Comment by Den-Valk** [comment]
Issue resolved. My installation of Java had become corrupted. I tested the server with a simple init script (just telling it to start, nothing more) and Java crashed. Upon re-installing Java, the noted problems from above disappeared. Thank you for your help, and I hope this solution helps others in the future.
Thank again jbondhus for your help.
