### ISSUE TITLE
find line messes up the check_links section

### ISSUE THREAD

**Issue by arjag42** [Ahtenus/minecraft-init#122]
Hi,

I was busy working on my server and implementing this script. Very nice btw.

I found an issue that may cause others to have issues.

The line 
as_user "find -L $MCPATH -type l -delete"
causes the script to keep removing the previously made links until you are only ever left with one.
I commented this line out and it works great.

Thanks for the hard work done by everyone.

**Comment by Ahtenus** [comment]
Seems to be a problem with that update yes, didn't really check that much before i accepted it (seem like a good idea). The line is now removed.
