### ISSUE TITLE
No 'Worlds' Listed

### ISSUE THREAD

**Issue by xptical** [Ahtenus/minecraft-init#13]
Hi all,

I'm using the script to launch a bukkit server.  It launches a stock world named 'world'.

I can connect to the server with no problems.  Everything _seems_ to work.

But if I do '/etc/init.d/minecraft worlds' I see nothing listed.  Since nothing is listed, I am unable to use the ramdisk option.

Also, there is no documentation on running multiple worlds.  I guess I could have several instances of the script run.  Is that the proper way?

Thanks.

**Comment by Benni-chan** [comment]
hi,

minecraft/bukkit doesn't know this launch script, so the worlds are created in the main folder.
after your worlds have been created, you have to move them to the folder specified by WORLDSTORAGE in the script. (see point 3 in the readme file)

once your worlds are in the specified folder, you can use all the features like ramdisk etc.

for multiple worlds, you don't have to runmultiple instances of the script. just use a multiworld mod for bukkit and create all the worlds you want. just make sure, you move them to the WORLDSTORAGE folder after creation. (stop the server when moving a world.)

**Comment by xptical** [comment]
Should the worlds in WORLDSTORAGE be in their own sub-directories?

i.e. /home/user/worldstorage/world1/

**Comment by Ahtenus** [comment]
Yes
