### ISSUE TITLE
Send command to the server from the commandline using this script.

### ISSUE THREAD

**Issue by Leopere** [Ahtenus/minecraft-init#133]
service minecraft-init command /blabla x y andZ
echo server response.
This would be a phenominal feature to add that wouldnt cost to much in devtime I think that someone somewhere has already done this with another init script but I dont have it on hand at the moment I will try and find it and post it here.

**Comment by stuxcrystal** [comment]
It wouldn't. I will make a pull request to add this feature... Unfortunately it won't allow you to receive the response.

**Comment by stuxcrystal** [comment]
#134 the pull request

**Comment by Leopere** [comment]
Wow that's fantastic I deeply appreciate this I can now send different commands via cron woot!  When I get back to a computer I'll look around more for that one script I mentioned but the echoed response really isn't a huge problem so I'm more then content with this :)
