### ISSUE TITLE
Trying to hack this to work with MCPC for FTB and forge

### ISSUE THREAD

**Issue by Leopere** [Ahtenus/minecraft-init#135]
http://i.imgur.com/e15tHLd.png Getting this on my startup of the server.
https://gist.github.com/chamunks/ec02e8a3b7bb62471bf6 is my config

**Comment by tillmzw** [comment]
How does your initscript look like? The `grep` errors look like syntax errors in the init.d script.

**Comment by Leopere** [comment]
I believe I'm using the vanilla init right off of the Git repo

**Comment by tillmzw** [comment]
Mind posting it?

**Comment by Leopere** [comment]
https://gist.github.com/chamunks/5e60c88f995f86ff4561

**Comment by Leopere** [comment]
The issue here is that grep is only looking for spiggot/bukkit output if it could be updated to see some of the forge output at the beginnings of the server init then we would be right as rain.
