### ISSUE TITLE
/etc/init.d/minecraft: 418: Bad substitution

### ISSUE THREAD

**Issue by xmagicx60** [Ahtenus/minecraft-init#14]
Everytime I try to start the script, this happens... Idk why... any help? All the directories are pointing to the right place...

**Comment by Ahtenus** [comment]
Hard to say with so little info, could you try to find any related log messages and post the settings you have for the script?

**Comment by xmagicx60** [comment]
I don't even remember posting that. Anyhow, I recreated the error, It was a simple linking error.
