### ISSUE TITLE
Log Roll rolling blank file.

### ISSUE THREAD

**Issue by DenValk** [Ahtenus/minecraft-init#154]
/etc/init.d/minecraft log-roll produces a backed up log file that contains only the line

Previous logs rolled to /home/**/**/**/Logs/logs_Year-Month-DayTTime

Please advise. I honestly don't know where to start debugging this one. Thanks, and thanks for the tool. It makes running a server SO much easier.

-DV

PS. I am comfortable making any changes and helping with any repairs. I just don't know where to start with this one. Let me know what information you would like etc..

**Comment by alfonsojon** [comment]
This would because logs are now stored in server_dir/logs, rather than server_dir/server.log

I'll see if I can fix this.

**Comment by Ahtenus** [comment]
Merged #157 which should fix this.
