### ISSUE TITLE
I'm Confused

### ISSUE THREAD

**Issue by ghost** [Ahtenus/minecraft-init#167]
So the part of the setup tutorial says to move my worlds into the worlds folder.

Does this mean I put the world in a folder in worlds?
Or do I put all the world files into that one folder? If this do I have the server.properties read out of that folder too?

This is the one part confusing me... >.<

**Comment by Ahtenus** [comment]
Using the default config, create a directory `worlds` in the minecraft directory and then move the folder `world` into `worlds`.

**Comment by ghost** [comment]
Ok thanks. :D
