### ISSUE TITLE
Seems like this script needs some updating....

### ISSUE THREAD

**Issue by flaminSaganaki** [Ahtenus/minecraft-init#19]
Hey, thanks a ton for the script. Its been great since i started using it. BUT, with the release of MC 1.0, it seems there should be some updates to the script. Worlds are handled differently, etc.
Also, i was hoping to recommend that you add a feature to group world backups in folder according to their dates. At the moment they are all clustered in 1 folder, and for me who has the backup run hourly, the folder is getting to be huge. It would be great if it could group them into folders by their date. Thanks!

**Comment by Ahtenus** [comment]
Could you please point out the differences?

**Comment by fdobrovolny** [comment]
Saving worlds is diferent, now is´nt exist World_nether ... now in folder World is folder DIM-1 it´s Nether and DIM-2 it´s End World

**Comment by melwil** [comment]
Also, they have started realeasing versions of craftbukkit taht follows another pattern, not just snapshots;
craftbukkit-"minecraft-version"-"release".jar

Updates need modification, and also how the jar for launching the game is detected.

**Comment by Ahtenus** [comment]
I can see now that the worlds are handled differently when installing a local server to test the script out. A solution would probably be to make the script more generalized so any sub folder of worldstorage containing the file ramdisk would be handled in the ram. 

Regarding the update function a reg exp of the download page could work but the problem would be that one would still need to change the `SERVICE` variable in the script. I'll have to think about that one.

**Comment by Ahtenus** [comment]
I'll try to look into it soon

**Comment by Benni-chan** [comment]
was about to say, the script already works that way, but i should really read the complete thread :)
will have a look at it

another thing i'd like to add is an install function, to create those folders inside worldstorage and create the links, so no server restart is necessary.

i just thought about changing the update function, too.
i believe, it's best to create a variable, defining if the user wants to use vanilla or bukkit.
the update function should only download the necessary build (so if the user wants to use bukkit, don't download the vanilla server). also we could add the possibility to download either the latest recommended build or the latest successful build.

is it really necessary, that the user can define, how he called his server.jar file? it would be much easier, if we use the default name from the dev team or our own (eg. craftbukkit.jar).

Update:
currently the bukkit build still creates several folders for the worlds, the vanilla server doesn't.
i have to think about this some more :(

**Comment by Ahtenus** [comment]
Could you clarify your thought on an install function?

Agree with you on the thoughts of the update function and I neither see any point in that users can define the name of the server.jar. 

So the script still works as it has done before for bukkit you say? If it does, my thoughts on a more genaralized one would work my thoughts are that 
`/etc/init.d/minecraft ramdisk world/DIM-1`
would add DIM-1 to ram and 
`/etc/init.d/minecraft ramdisk world`
would add the whole world to ram

**Comment by Benni-chan** [comment]
an install function could create the necessary folders (worldstorage, backup, etc), change ownership and permissions (if necessary) and also create the world folders inside worldstorage (for each world if bukkit is used, or only world, if vanilla is used) and link them to the maindir.
This way, minecraft will create the worlds directly inside the worldstorage folder and no restart to move the worlds is necessary. (have to test first, if minecraft creates a world, if the folder already exists, but I believe so, if the folder is empty.)
we could also create the cronjobs for the user.

At the moment at least, the script works as it should with bukkit.
to use the commands like you described, there would be a few modifications necessary, but should be manageable.

btw. I found one reason to rename the server.jar... if a user has more than one server on one machine, the script believes, the server is already running. but if each server has an unique filename, the server starts just fine.
so we have to either change the test routine, that checks, if the server is running, or we still use a variable for the name of the server.jar.

I would recommend to use a variable for the name, but use the same name for either a vanilla or a bukkit server (which is determined in an other variable).
so the update function would only download the necessary jar file and save it under $server_file.jar

**Comment by Ahtenus** [comment]
The install idea seem nice. I think a separate install.sh file would make most sense.

Yup, a special variable  seem like the best solution.

Okay, good that the script works for bukkit. You seem to be eager to update the script, do you want to update the ramdisk functions as well or should I do it?

**Comment by Benni-chan** [comment]
i don't have much time currently, so feel free to do it :)
i would probably start in one or two week at the earliest.

**Comment by flaminSaganaki** [comment]
This all sounds great but id like to add something about how worlds are handled. 
Currently with mc 1.0, there are 3 seperate worlds: world, nether, theEnd.
All are being loaded onto the ramdisk with the script at this time, but i find it rather unnecessary to load theEnd world when it is hardly ever loaded by a player. So maybe have it so that it only loads its onto the ramdisk when a player(s) enters the ender realm? It would prob save good amount of resources for the world that really needs ramdisk the most. Just my thoughts...
Also now that i think about it the nether world would also benefit from this same idea. So maybe have both theEnd and the Nether not loaded onto ramdisk until/unless player enters them.

**Comment by flaminSaganaki** [comment]
And once again i will request that something be done about how backups are stored.
At the moment the script just piles them all up in one folder. But for the majority of us who like to run hourly backups etc, it would be so great if inside the main backup folder, subfolders were to be created for every day. It would be so much better organized and convenient.

**Comment by Ahtenus** [comment]
Daily folders is easily done and seems like a good idea. So I'll implement it.

As ramdisk is more of a workaround for the minecraft servers poor memory handling, it's better to improve the memory handling in the server software instead of trying to dynamically move worlds back and forth into ram. As it would be very impractical to do such in a shellscript.

**Comment by Ahtenus** [comment]
I gave the generalized ramdisk idea a shot, but it was more complicated than expected, so I'll leave it for now.

**Comment by jbondhus** [comment]
Do you think we can close this issue? It's been open for a year now and is just filling up the queue.

**Comment by Ahtenus** [comment]
Yeah, you are probably right.
