### ISSUE TITLE
Unknown id: v

### ISSUE THREAD

**Issue by neavea** [Ahtenus/minecraft-init#20]
I have everything setup (I think) and when I initiate it or even type /etc/init.d/minecraft start it gives me this:

links checked
craftbukkit-1.0.0-SNAPSHOT.jar was not running... starting.
Unknown id: v
Could not start craftbukkit-1.0.0-SNAPSHOT.jar.

I am not sure if its because I am using it with bukkit 1.0.0 or if I installed screen wrong. man screen says I should setup my terminals but I don't know how to do that beyond tset. Looking at your code the problem occurs when it tries to set the command -v into screen?

**Comment by Benni-chan** [comment]
you probably didn't change this line:
USERNAME="v"

you have to set it to the user, which should run minecraft.

**Comment by Ahtenus** [comment]
Do you have the correct settings, specifically the username variable?
Den 4 dec 2011 19:47 skrev "neavea" <
reply@reply.github.com

**Comment by neavea** [comment]
I ment to post the day of but my issue was indeed that the username was set wrong. on a side note, your if statements seem wrong.
"if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null" I changed the SCREEN section to $SCREEN. I don't know if thats what is supposed to be but my init scripts work with that change.

**Comment by Ahtenus** [comment]
The line is correct in the script.

It searches for a minecraft_server.jar/craftbukkit (using the $SERVICE variable) and excluding the grep itself as well as screen from the search.
