### ISSUE TITLE
Can't connect to screen

### ISSUE THREAD

**Issue by claytonraymond2004** [Ahtenus/minecraft-init#24]
Everything seems to be running perfectly with the script except I can't seem to be able to connect to the screen with the server console. (Server is running under the user "minecraft" on my server) I log in as administrator to my server.

I've tried:
screen -x minecraft
sudo screen -x minecraft

All of which get: There is no screen to be attached matching minecraft.

I've also tried:
sudo su minecraft
then
screen -x minecraft

Which gives: Cannot open your terminal '/dev/pts/5' - please check.

(I've tried all of the commands with the -r flag instead of -x flag and get the same result.

Any help would be greatly appreciated.

**Comment by Ahtenus** [comment]
Login to the user running the server (using su)
Then screen -r minecraft
Den 25 dec 2011 01:50 skrev "claytonraymond2004" <
reply@reply.github.com

**Comment by claytonraymond2004** [comment]
I tried that with the same result. Perhaps the user (minecraft) is not setup correctly? The user has /bin/bash for shell, is not allowed to login and therefore has no password, and is a member of no groups.
"I've also tried:
sudo su minecraft
then
screen -x minecraft

Which gives: Cannot open your terminal '/dev/pts/5' - please check."

Thanks

**Comment by claytonraymond2004** [comment]
I figured a way around. I had to reset some permissions on /dev/pts/\* and now it works. Thanks.
