### ISSUE TITLE
Support for Minecraft Overviewer

### ISSUE THREAD

**Issue by RogerSik** [Ahtenus/minecraft-init#25]
Hello
it would be great when it gives a option like

service minecraft overviewer

which stop the minecraft server for overviewer.

https://github.com/overviewer/Minecraft-Overviewer

**Comment by Ahtenus** [comment]
I won't add it, but give me a pull request if you decide to do it yourself.

**Comment by wboubi** [comment]
HI,

I have modified the script to add the function.
You need to configure the path in the config file and call the script with : minecraft overviewer WORLD.

I send a pull request.

**Comment by RogerSik** [comment]
Hi,

thanks wboubi. :)

**Comment by Ahtenus** [comment]
Good work, it's now in master as well :)
