### ISSUE TITLE
trouble with getting the script to work

### ISSUE THREAD

**Issue by Llesari** [Ahtenus/minecraft-init#28]
THIS WAS MY OLD ISSUE LOOK TOWARDS THE BOTTOM

well i am sort of new to linux but i managed the setup to what i believe  was right but i cant get it to work i tried to use the help command you supplied but it just gives me a message saying rename config.example to config i have already done that and it just tells me to do it when i use screen minecraft it says no such script.

forget that i got it to work very nicely thank you but do you know how i can get the screen to work in ssh?

**Comment by Ahtenus** [comment]
It should work just as is, just make sure to log into the account running the minecraft server
    ssh mincraft@yoursever
    screen -r minecraft

Also: always write what you did to solve the problem, in case anyone else runs into the same one.
