### ISSUE TITLE
Datepath makes invalid paths

### ISSUE THREAD

**Issue by Knuffle** [Ahtenus/minecraft-init#3]
When trying to do a log-roll, I run into this error message:

mv: cannot move `/home/mineadmin/server.log' to`/home/mineadmin/logs/server_05/29/2011.log': No such file or directory

i think the problem is in the date "05/29/2011" as it is looking for the directory "05" and the sub directory "29"

**Comment by Ahtenus** [comment]
Apparently `date +%x` returns differently depending on your locale... Changed to `date +%F` which should return the same everywhere.

Thanks for pointing it out :)
