### ISSUE TITLE
to_disk() doesn't check to see if world isn't a ramdisk

### ISSUE THREAD

**Issue by jjcf89** [Ahtenus/minecraft-init#31]
Calling minecraft stop reports that it has moved several worlds from ramdisk even though only one is actually on the ramdisk.  

I currently only have the main world folder put on the ram disk and not the world_nether and world_the_end but they get copied to disk anyway.  I'm unsure if this actually hurts anything but figured I'd point it out.

**Comment by Ahtenus** [comment]
Could you start the minecraft server and then list the directorys in
/dev/shm aswell as worldstorage and post it here?

**Comment by jjcf89** [comment]
$ls /dev/shm
pulse-shm-3583870172
pulse-shm-3830334793
world
$ls worldstorage
world
world_nether
world_the_end

**Comment by Ahtenus** [comment]
Okay, everything seems to be in order, only the messages that are a bit
misleading. What the script does is create symlinks between your minecraft
folder and worldstorage for each world.

**Comment by Ahtenus** [comment]
So the script copies folders from worldstorage containing the file ramdisk
to the ram and links them into the minecraft folder. While the other
folders gets symlinked from worldstorage directly.

Don't know if that answers your question/notice.

**Comment by jjcf89** [comment]
Yeah just wasn't sure if rsync might cause any problems copying a folder to itself.

**Comment by Ahtenus** [comment]
Okey, looked at the source and you are indeed correct, didn't really understand what you meant until now. It should be patched now.

**Comment by jjcf89** [comment]
Thanks for the quick response.
