### ISSUE TITLE
Craftbukkit updates don't seem to work.

### ISSUE THREAD

**Issue by Remanent** [Ahtenus/minecraft-init#33]
While the url in your script works in a webbrowser, it doesn't seem to fetch the file for some reason.  there is also an http redirect link available, but that didn't seem to work either when i plugged it in place of the url you provided in your script.

script url on line 267 = http://ci.bukkit.org/job/dev-CraftBukkit/lastSuccessfulBuild/artifact/target/
http redirect provided by bukkit.org = http://repo.bukkit.org/service/local/artifact/maven/redirect?g=org.bukkit&a=craftbukkit&v=RELEASE&r=releases

**Comment by wboubi** [comment]
Hi

The script get the latest development release.
In the script we have 2 lines to fetch the file. 

The line 267 :
`CB_URL="http://ci.bukkit.org/job/dev-CraftBukkit/lastSuccessfulBuild/artifact/target/"
`
The line 268 :
`CB_SERVER_URL=$CB_URL`wget -q -O - $CB_URL | grep \>craftbukkit | cut -d \" -f 30`
`

The second line parse the page to get the file name (for new release).
The result of the 2 command is :
```echo $CB_SERVER_URL
http://ci.bukkit.org/job/dev-CraftBukkit/lastSuccessfulBuild/artifact/target/craftbukkit-1.1-R4-SNAPSHOT.jar

``````

If you want to add the url provided by bukkit just comment line 267 and 268 and add this line :
```CB_SERVER_URL="http://repo.bukkit.org/service/local/artifact/maven/redirect?g=org.bukkit&a=craftbukkit&v=RELEASE&r=releases"
``````

**Comment by Remanent** [comment]
Commenting out lines 267 and 268, and adding the line you provided, placed on line 269 create this in the console when it attempts to update craftbukkit....

<code>Updating craftbukkit....
bash: amp: command not found
bash: amp: command not found
bash: amp: command not found
CraftBukkit update could not be downloaded.
