### ISSUE TITLE
server doesn't start at system boot, did with previous script that didn't use seperate config file

### ISSUE THREAD

**Issue by Remanent** [Ahtenus/minecraft-init#35]
the previous version of your script used to load the server at system boot w/o having to login to the system and execute 'minecraft start'.  current script does not load.  do i need to somehow add the config file to the system boot process or something?

**Comment by Remanent** [comment]
As a workaround, i commented out lines 23-36 which were used to load the config file, then copied the contents of the config file back to the script, and placed them below line 38, so all the config options were now in file with the rest of the script.  The script appears to be functioning correctly, and the server does load at boot time w/ the update-rc.d in place.  not sure why it wasn't loading with the script as you distribute it.  if you know where i can find the error log so that there is more information to be shared, i'll gladly share it.

**Comment by Ahtenus** [comment]
Finally took the time to look at it. It was a bug with loading the config if the script was called using nested symlinks. So in the latest version it should be fixed.
