### ISSUE TITLE
Add date to ouput

### ISSUE THREAD

**Issue by ikehoff** [Ahtenus/minecraft-init#37]
To make log files easier to track. Not every line needs to be dated, just insert one line with the date.  To make reading appened cron output logs easier.  I'm guessing make a date() funtion and call it later on. so it outputs only one date line per backup/restart/log-roll etc...

**Comment by Ahtenus** [comment]
Won't be fixed. I find the server.log to be best left as is. Adding such a function would just complicate matters unnecessarily.

**Comment by ikehoff** [comment]
I'm sorry, I misspoke.  I am referring to stdout during execution of commands.  I have already implemented this feature myself. Thanks :)

ex: /etc/init.d/minecraft backup
date
blah
blah
blah

**Comment by Ahtenus** [comment]
So you save the output from the init script somehow? 
I guess more extensive usage of the system logger could be used (in a separate file). 
Don't see much usage in it though.

**Comment by ikehoff** [comment]
Yes. /etc/init.d/minecraft backup >>/minecraft/cron.log
2>>/minecraft/cronerr.log

This is part of my crontabs execution line. So when I look at the logs, it
shows when it executed/errored
On Feb 6, 2012 3:58 PM, "Ahtenus" <
reply@reply.github.com>
wrote:

**Comment by Ahtenus** [comment]
Ok, I see. The majority of the users probably don't save logs that way and it would make the output even more verbose than they already are. But more extensive use of the syslogger (via the command logger) could probably be used. Nothing I'll add any time soon though.
