### ISSUE TITLE
Update Command

### ISSUE THREAD

**Issue by mkromann** [Ahtenus/minecraft-init#41]
First of all, absolutely love the work you're doing here. Thank you.

I just read the frontpage of bukkit.com and stumbled upon http://forums.bukkit.org/threads/introducing-dl-bukkit-org.59836/.

I was just wondering if the update command reflects the new changes? I does seem like there is a more intuitive way to download the latest version of Craftbukkit than before.

I don't know if this is relavant but just wanted to point you to it.

**Comment by wboubi** [comment]
Hi Infuscu,

The update command get the latest Development build.

I have started to work on a new update method who get the latest recommended build.

**Comment by Ahtenus** [comment]
Good that you find it useful, and thanks for the update.

@wboubi Good, I'll merge it in.
