### ISSUE TITLE
ramdisk

### ISSUE THREAD

**Issue by tanertopal** [Ahtenus/minecraft-init#45]
How can i see if ramdisk is enabled? I try: 

/etc/init.d/minecraft ramdisk world

then i get the following error:

World "world" not found.

How can i find out the world name?

**Comment by Ahtenus** [comment]
It's the name of the folder...

**Comment by tanertopal** [comment]
Hey ty,

solved the problem. I had not copied the worlds into the worldstorage folder. Does ramdisk make any sense on a VS? Sadly i couldnt see any Change in FPS.

**Comment by Ahtenus** [comment]
If you with VS mean Virtual server, then it probably does. Disk IO is far slower than ram IO. FPS has nothing to do with the server. It speeds up getting world chunks from the server.

**Comment by tanertopal** [comment]
I mean virtual server, right. In my MinecraftClient FPS and Chunks per
Second are allways in sync... so i thought its the same at least in
Minecraft. Usally its something around 100. Any way to benchmark in
MinecrafT?

2012/2/28 Ahtenus
reply@reply.github.com:

**Comment by Ahtenus** [comment]
Chunks as in world chunks from the server, has no correlation with FPS. You'll notice it when you teleport or travel. If the server disk IO is slow you'll see big holes in the world that will disappear once the server catches up and sends those world chunks to you.
