### ISSUE TITLE
Backups are corrupted?

### ISSUE THREAD

**Issue by melwil** [Ahtenus/minecraft-init#47]
I tried to extract a backup of my survival_nether world;

<pre>
minecraft@bacardi:~$ tar -jxvf survival_nether_2012-03-01.tar.bz2

bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
</pre>

Is there a special way to extract backups, or are the files really corrupted? I get the same for all the backups I have stored.

**Comment by jjcf89** [comment]
I was able to extract my backups using your command.

**Comment by Ahtenus** [comment]
The worlds are compressed with the command

```
tar -hcjf $path $MCPATH/${WORLDNAME[$INDEX]}
```

so nothing special should be needed, seems like your files are in fact corrupt.

**Comment by melwil** [comment]
Alright, I guess I'll have to investigate further on my end then, thanks for the replies.

**Comment by Ahtenus** [comment]
Do so and please report back if you found it had something to do with the script :)
