### ISSUE TITLE
Unknown id

### ISSUE THREAD

**Issue by cskiwi** [Ahtenus/minecraft-init#49]
Hi, I'm getting the following error:

unknown ID: kiwi

but the thing is I launch from it from the kiwi acc:

kiwi@bubblegum:~$ /etc/init.d/minecraft start
: No such file or directoryi
links checked
: No such file or directoryi
: No such file or directory 73: cd: /home/kiwi
Unknown id: kiwi

directory looks like following:

http://screencast.com/t/LhboFds4
everything is in that file, I don't get it

already thanks: kiwi

**Comment by Ahtenus** [comment]
What does

```
cat /etc/passwd
```

output?

**Comment by cskiwi** [comment]
This is the output:```
root@bubblegum:~# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/bin/sh
bin:x:2:2:bin:/bin:/bin/sh
sys:x:3:3:sys:/dev:/bin/sh
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/bin/sh
man:x:6:12:man:/var/cache/man:/bin/sh
lp:x:7:7:lp:/var/spool/lpd:/bin/sh
mail:x:8:8:mail:/var/mail:/bin/sh
news:x:9:9:news:/var/spool/news:/bin/sh
uucp:x:10:10:uucp:/var/spool/uucp:/bin/sh
proxy:x:13:13:proxy:/bin:/bin/sh
www-data:x:33:33:www-data:/var/www:/bin/sh
backup:x:34:34:backup:/var/backups:/bin/sh
list:x:38:38:Mailing List Manager:/var/list:/bin/sh
irc:x:39:39:ircd:/var/run/ircd:/bin/sh
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/bin/sh
nobody:x:65534:65534:nobody:/nonexistent:/bin/sh
libuuid:x:100:101::/var/lib/libuuid:/bin/sh
syslog:x:101:103::/home/syslog:/bin/false
messagebus:x:102:105::/var/run/dbus:/bin/false
postfix:x:103:109::/var/spool/postfix:/bin/false
dovecot:x:104:111:Dovecot mail server,,,:/usr/lib/dovecot:/bin/false
dovenull:x:105:65534:Dovecot login user,,,:/nonexistent:/bin/false
landscape:x:106:112::/var/lib/landscape:/bin/false
sshd:x:107:65534::/var/run/sshd:/usr/sbin/nologin
kiwi:x:1000:1000:kiwi,,,:/home/kiwi:/bin/bash
mysql:x:108:117:MySQL Server,,,:/nonexistent:/bin/false
ftp:x:109:118:ftp daemon,,,:/srv/ftp:/bin/false
gerrit:x:1001:1001:,,,:/home/gerrit:/bin/bash

```
```

**Comment by Ahtenus** [comment]
Your account is there and it seems to be in order, but for some reason `su` falls. Seems to be something related to the kiwi account or script settings.

**Comment by cskiwi** [comment]
Hmm that's strage, because the only change was an update of the script, but that made every thing crash.

Thanks anyway

**Comment by TyOverby** [comment]
Do you happen to remember what the change was?

**Comment by cskiwi** [comment]
yea I changed my RAM, but an reinstall of the script made everything work again

**Comment by carlazas** [comment]
Firts of all, sorry for my bad english.

I had a similar problem. After a lot of time trying differents things finally i found that after abort the script manually while "still not running..." there was an error message whith an address... and on this addres were "/r" just after every field you can define in config file.

i am still look out why my computer (proliant 110, ubuntu server 12.04 lts) do that, but ending code lines with comment in config file made the script works

**Comment by jbondhus** [comment]
Install the package `dos2unix` and run it on both the config file and the script file. The syntax is `dos2unix [filename]`, where `[filename]` is the file you want to run it on.
