### ISSUE TITLE
Automatic restart

### ISSUE THREAD

**Issue by Trikolon** [Ahtenus/minecraft-init#53]
It would be cool if someone could add an automatic restart paramter to start the script with. It should warn the users longer then and check if the server is still reacting and killing it if not.
And also, what about this check? Can the script check if the server is still working, like if its frozen?

**Comment by Remanent** [comment]
This is a script, and not an active program.  It has no way to monitor the life (active or frozen status of the server)  while it does have a restart function you can call via cronjob if you want it to say reload every 24 hours or something, it can't sit there and go i'm watching the server all day long unless you have it ran every few seconds / minutes / w/e time you setup via a cronjob to check the server status.

**Comment by Trikolon** [comment]
Yeah, what about a function that checks if the servers is not frozen etc. ? Users can decide if they want to use it with a cronjob then.
