### ISSUE TITLE
Overviewer usage outdated

### ISSUE THREAD

**Issue by lolmaus** [Ahtenus/minecraft-init#56]
Hi!

Overviewer has been developing recently.

Firstly, it's preferred installation method is now via apt package manager. It installs `overviewer.py` into `/usr/bin` and the rest of Overviewer into some other place. Because of that, the `$OVPATH` directory is now confusing.

Secondly, Overviewer configuration syntax and structure have changed. You should now provide paths to worlds within Overviewer config, not command line. Also, `--settings` has changed to `--config`.

According to Overviewer developer `agrif`, the correct Overviewer command is the following:

```
python overviewer.py --config=/path/to/config.txt
```

Don't take my considerations for granted, please double-check before modifying your beautiful code.

**Comment by lolmaus** [comment]
Also, you don't need to stop Minecraft server for Overviewer to render the map. Rendering may take hours, which means hours of server downtime. Unacceptable!

Instead of server off/on, do save off/on! In between, copy `worldstorage` to another location using `rsync -a --delete`. Copying should take seconds instead of hours. After resuming saves, start Overviewer.

Overviewer config should contain paths to the copy of `worldstorage` worlds.

**Comment by Rovanion** [comment]
> Firstly, it's preferred installation method is now via apt package manager.

Everyone doesn't use a Debian based OS and others yet prefer to clone the git repo directly. So I would still keep the $OVPATH variable in place. Maybe change the default in config.example but nothing more.

**Comment by lolmaus** [comment]
> Everyone doesn't use a Debian based OS and others yet prefer to clone the git repo directly. So I would still keep the $OVPATH variable in place. Maybe change the default in config.example but nothing more.

Oh come on, i didn't mean you should change variables. I thought you'd make a note in comments for Debian-based users.

How about the rest of the issue?

**Comment by Rovanion** [comment]
I thought you wanted to remove the variable. The rest seems fine to me.

**Comment by wboubi** [comment]
I just send a pull request to fix the issue.
