### ISSUE TITLE
Distribute the 'config' file instead of the 'config.example' file.

### ISSUE THREAD

**Issue by TyOverby** [Ahtenus/minecraft-init#58]
By distributing the file as "config" instead of "config.example" you do two things:
- Make it easier for new users to get it up and running.  I know that I didn't see the instructions to rename it for a while.  (this isn't very important).
- When the config gets updated on github and we pull from the repository, it will generate diffs for us that let the users easily notice where parts of the config change.  It also has the added benefit of keeping all their custom settings (that didn't change) as well as clearly marking the parts that did change.

**Comment by Ahtenus** [comment]
The file is named config.example so that you can have custom settings when developing the script. Saves a lot of trouble when committing and pushing upstream.

Comparing files can be easily done with `diff` anyway...
