### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by Westoya** [Ahtenus/minecraft-init#6]
Could the init script be modified to include the switch 'version'? "/etc/init.d/minecraft version" would output which version of craftbukkit is currently being run. 1.7, 1.7.01, etc.

**Comment by Ahtenus** [comment]
My minecraft server i currently facing some hardware hiccups so I won't implement it at the moment. But if anyone submits a patch I'll gladly accept it. A simple grep in the log file would probably do the trick.

**Comment by karrth** [comment]
I added this to my fork and submitted a pull request for you:
https://github.com/karrth/minecraft-init/commit/51abbd6860d4d72c45ed3f74fe14ad0e9af01655

**Comment by Ahtenus** [comment]
Merged.
