### ISSUE TITLE
Timed start/stop

### ISSUE THREAD

**Issue by Trikolon** [Ahtenus/minecraft-init#61]
What about timed start and stops e.g. : ./minecraft stop 10 (server stop in 10 seconds)
This could be also broadcasted on the server then.

**Comment by Ahtenus** [comment]
The script already waits 10 sec for the server to save the worlds, I think that's sufficient.

**Comment by Ahtenus** [comment]
You can use the sleep command like this to make it wait 20 seconds:

```
minecraft say "Server shutting down in 20 seconds"; sleep 10; minecraft stop
```

**Comment by Trikolon** [comment]
Oh okay, thank you. The feature is not necessarily then.
