### ISSUE TITLE
Backup Script Still Making Date folder

### ISSUE THREAD

**Issue by jbondhus** [Ahtenus/minecraft-init#64]
It's still making the folder for the date when the mode for compatibility with the backup rolling script is enabled in the config file. It still works fine, but it's kind of annoying, and should be fixed because every day it makes one more empty folder, and after a week you'd have seven folders. Eventually it would get kinda messy.

**Comment by jbondhus** [comment]
I took a look at the script myself. Like I said, I'm not expert with bash, in fact I have virtually no previous experience besides examining and messing around with your script, but I think I fixed the problem. This modified mc_world_backup function should get the job done and only create the today folder if the script rolling compatibility feature is enabled. If and only if it is enabled, it will also erase the previous backup of the one it is about to backup so that it can overwrite it properly, and will output to the console that it is doing so. That way it doesn't erase previous backups every hour which would defeat the point of backing up. If this looks OK, please consider adding it to your code, as it should do the following new things only if  compatibility with the rolling backup script is enabled in the config. I have tested it out myself and found it to work, however, I would recommend testing it out yourself as I have a slightly different setup.

``` bash
mc_world_backup() {
    #
    # Backup the worlds and puts them in a folder for each day (unless $BACKUPSCRIPTCOMPATIBLE is set)
    #

    get_worlds
    today="`date +%F`"
    for INDEX in ${!WORLDNAME[@]}
    do
        echo "Backing up minecraft ${WORLDNAME[$INDEX]}"
        case "$BACKUPFORMAT" in
            tar)
                if [ "$BACKUPSCRIPTCOMPATIBLE" ]
                    # If is set tars will be put in $BACKUPPATH without any timestamp to be compatible with
                    # [backup rotation script](https://github.com/adamfeuer/rotate-backups)
                then
                    echo "Deleting old backup of ${WORLDNAME[$INDEX]}"
                    as_user "rm -r $BACKUPPATH/${WORLDNAME[$INDEX]}.zip"
                    path=$BACKUPPATH/${WORLDNAME[$INDEX]}.tar.bz2
                else
                    as_user "mkdir -p $BACKUPPATH/${today}"
                    path=`datepath $BACKUPPATH/${today}/${WORLDNAME[$INDEX]}_ .tar.bz2 .tar.bz2`
                fi
                as_user "tar -hcjf $path $MCPATH/${WORLDNAME[$INDEX]}"
                ;;
            zip)
                if [ "$BACKUPSCRIPTCOMPATIBLE" ]
                then
                    echo "Deleting old backup of ${WORLDNAME[$INDEX]}"
                    as_user "rm -r $BACKUPPATH/${WORLDNAME[$INDEX]}.zip"
                    path=$BACKUPPATH/${WORLDNAME[$INDEX]}.zip
                else
                    as_user "mkdir -p $BACKUPPATH/${today}"
                    path=`datepath $BACKUPPATH/${today}/${WORLDNAME[$INDEX]}_ .zip .zip`
                fi
                as_user "zip -rq $path $MCPATH/${WORLDNAME[$INDEX]}"
                ;;
            *)
                echo "$BACKUPFORMAT is no supported backup format"
                ;;
        esac
    done
}
```

**Comment by Ahtenus** [comment]
Thank you! I apperently missed that. Your fix is now merged into the main branch.
