### ISSUE TITLE
Whole-backup and DynMap (plugin)

### ISSUE THREAD

**Issue by mkromann** [Ahtenus/minecraft-init#69]
I've stumbled into a problem after enabling DynMap high definition renders. The size of my DynMap folder is enormeous (22gb) and that in itself is not really a problem. What is a problem, however, is when I do whole-backup's, as they literally takes a few hours (I do them a few times a week).

Can I get around this problem in anyway? Excluding the DynMap plugin folder from the backup or something like that?

Has anyone else had this issue?

**Comment by jbondhus** [comment]
Maybe a script that **moves** it to a different folder right before it backs up. Just put it in your crontab. Moving it versus copying it should be instant.

**Comment by sockenklaus** [comment]
I made a pull-request (#91), that actually gives you the option to add certain files and directories to an exclude.list to prevent them from being backed up.

**Comment by tuxillator** [comment]
this should probably be closed, with the above PR merged adding plugins/dynmap/web/tiles to exclude.list now prevents massive backups with Dynmap installed.
