### ISSUE TITLE
Nether support

### ISSUE THREAD

**Issue by oparisy** [Ahtenus/minecraft-init#7]
It seems like the nether world is not supported for now. The first time I reached it through a portal, a server/world_nether folder was created on my craftbukkit installation (Build #935). So It seems like this nether world is neither on the ramdisk nor backed up.

As an aside, I could not break blocks nor build anything in the nether. Could it be related?

**Comment by Ahtenus** [comment]
I have not included the nether into the ramdisk because it's hardly used on my server, the ram is better used for the server itself. That it's not backed up is more of lazyness though. Will maybe fix it some day, still don't have a working server to test it on though.

**Comment by razzeeyy** [comment]
Hi, i have modified script a little to provide world_nether and world_skylands support for bukkit. Use it on your own risk!

http://alexzero92.narod.ru/minecraft

Installation the same but in item 3 you must rename all of your worlds:

cd ~/minecraft
mv world diskworld
ln -s /dev/shm/world world
mv world_nether diskworld_nether
ln -s /dev/shm/world_nether world_nether
mv world_skylands diskworld_skylands
ln -s /dev/shm/world_skylands world_skylands

And remember to set right values to vars in script!
(NETHERSTORAGE - location of nether on disk, SKYLANDSTORAGE - location of skylands on disk.)
P.S. Dunno about necessary of filling skyland-related vars but fine if it works without.

**Comment by Benni-chan** [comment]
hi, i have a modified version for multiworld support, too.
the advantage of mine is, that you can use a free number of worlds and name them as you like.

http://mc.sternendreck.de/stuff/minecraft

the installation is the same as before. of course you have to link all worlds (only those, you want to run from the ramdisk) to the ramdisk.

in the config you have to set the right values for the DiskStorage and the WorldNames and if you want to use ramdisk for that world.

```
# name of the world (name in minecraft folder)
WORLDNAME[1]="world"
WORLDNAME[2]="world_nether"
# Where the world is located on the disk
WORLDSTORAGE[1]="/home/${USERNAME}/minecraft/diskworld"
WORLDSTORAGE[2]="/home/${USERNAME}/minecraft/disknether"
# copy world to ramdisk?
WORLDRAM[1]=true
WORLDRAM[2]=true
```

if you need more than two worlds, just add another WORLDSTORAGE, WORLDNAME and WORLDRAM line. Just make sure, that you use adjacent numbers starting with 1. don't jump from 2 to 4, for example!

if you don't want a world in ramdisk, simply set the WORLDRAM line for that world to false. (of course you mustn't link the folder for that world to the ramdisk in this case!)
in this case, the value for WORLDSTORAGE can be blank or anything you want.

with this script, even if you don't want the second (third, fourth) world in your ramdisk, the script will create a backup of it.

p.s. of course you can implement these changes in the "official" version, if you want

**Comment by Rovanion** [comment]
The file you linked, is the contents of it the same as your minecraft-init fork on github?

**Comment by Benni-chan** [comment]
hi, at first, it was, yes.
but now i changed some more things, so my fork is the most current version. (i mostly added some features/fixes from other forks.)

**Comment by Ahtenus** [comment]
Very nice, will add it to the official version as soon as I get my server up and running again which shouldn't be to far away.

**Comment by oparisy** [comment]
Great to read that those improvements will be merged in the main branch (do I sound like a CVS user?). I will not need to make my own mix :)

**Comment by Rovanion** [comment]
That sounds good, makes it easy to merge.

**Comment by razzeeyy** [comment]
Benni-chan good job! High class coding :)

**Comment by Benni-chan** [comment]
short info: just submitted some more changes in my fork.
now the links to the ramdisk will be created by the script. of no ramdisk is used, the link will point to the disk storage folder.

this enables easy switching on and off of ram disk use for single world, without manually moving folders. (also the initial setup is somewhat easier.)

i'm currently testing this on my server, so far, it works :)

**Comment by Ahtenus** [comment]
Benni-chan: Very nicely coded I must say.
The automatic symlinking simplifies the setup process a lot and the multiworld support is also very elegant.

Have now pushed the multiworld support and dynamical symlinking up stream ;)
