### ISSUE TITLE
Infinite backup files

### ISSUE THREAD

**Issue by hcase** [Ahtenus/minecraft-init#78]
I have this issue: Every day, a backup .tar.bz2 is normaly created. But it's bigger than the map herself. My map is 4 GB, and, depending of days, the backup file can be 10 GB to 45 GB ! When I untar the file, it takes hours, and finally crash, and I have a folder with inside it another folder "world", with inside it an other "world", etc etc, so finally I have /world/world/world/world/world... more than 40 times. In every "world", there is "players", "data", and "level.dat_mcr", and at the end, it seems to finally have "region". I'm not sure of that because untar crash every times (I think...). Cron run backup daily, the same way that it's write on the example page. Does someone have an explanation, and a solution for this?

Thanks, and sorry for my bad english :)

**Comment by Rovanion** [comment]
Wild guess: You are backing up a folder that has symlinks to it's parent directory, thus the loop. Go into your file hiarchy and look for some mysterious symlinks.

**Comment by hcase** [comment]
mmmmh there was a link into the world folder, which was pointing... to world folder... I deleted it, and i'll tell you tomorrow if it works, and close the issue if it's good :) Thanks!

**Comment by hcase** [comment]
It worked ! Thanks a lot :) Now I have good backup :p :p Thanks !
