### ISSUE TITLE
No links created if worldnames contain spaces

### ISSUE THREAD

**Issue by DHLF** [Ahtenus/minecraft-init#85]
If a world named "Test World" exists it is not possible to let the script create links.
As the get_worlds() function will treat each word separately:
name:="Test" 
name:="World"
instead of  name:="Test World"

get_worlds() {
a=1
for NAME in $(ls $WORLDSTORAGE)
do

I am sorry for not having a solution to solve this except one:
DONT use spaces in world names..

**Comment by sockenklaus** [comment]
Hi DHLF... i fixed this in in my pullrequest #94.

You can clone my repo here: 
https://github.com/sockenklaus/minecraft-init
