### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by DarkRedman** [Ahtenus/minecraft-init#86]
I'm working on ArchLinux I'm lauching minecraft server with that command :
rc.d start minecraft

and I got :

``` bash
/etc/rc.d/minecraft: line 217: syntax error near unexpected token `)'
```

But the script doesn't have a line 217.

How to fix it ?

**Comment by jbondhus** [comment]
Try the latest version and see if you still have this error. Apologies about the delay, I'm in college and don't always get around to checking through the issues.

**Comment by DarkRedman** [comment]
I finally fixed it since the last time. In fact the copy and paste into nano changed the "return" lines.
