### ISSUE TITLE
grep errors

### ISSUE THREAD

**Issue by ericwomer** [Ahtenus/minecraft-init#99]
im running craftbukkit on an amd 686 system and i get this running the minecraft init script.
rc-service minecraft start
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Rogue pidfile found!
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Rogue pidfile found!

**Comment by jbondhus** [comment]
I'm having the same issue... I thought it was my fault at first since I was working on merging my changes into the master version, but now that I tried running the master version it still doesn't work... with the exact same config file too.

**Comment by jbondhus** [comment]
Here's a trace of the script from the start to the end (I had to change it so that it waits 10 seconds after starting to timeout, so that it wouldn't trace for 120 seconds and leave a freakishly long log).

[http://pastebin.com/TKuubhda](http://pastebin.com/TKuubhda)

**Comment by croemmich** [comment]
For some reason the pid file is empty when server is started though the init script as a different user than the config user. I'm trying to see if I can solve this.
